---
# tasks file for kubenode
# ENable Kubernetes Repo
- name: Enable Kube Repo
  template: 
    src: kubernetes.j2
    dest: /etc/yum.repos.d/kube.repo
    owner: root
    mode: 644

- name: Enable Kube SysCtl Parameters
  template: 
    src: k8s.j2
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    mode: 644


#Install Packages
- name: Install Docker
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - vim
      - docker  
      - kubelet
      - kubeadm
      - kubectl


-   name: Disable Selinux
    selinux:
      state: disabled

-  name: Set k8s paramater for Kernel
   shell: sysctl --system
 
-  name: Enable k8s Services
   service:
     name: "{{ item }}"
     state: started
     enabled: yes 
   with_items:
       - docker
       - kubelet
